### ISSUE TITLE
UI: Very High: Search functionality not working

### ISSUE THREAD

**Issue by ChetanaKoulagi** [LetsTagOn/LetsTagOnThoughtClan#10]
1. If I search for any registered volunteer, it does not show relevant search results. It just lists everyone or anything.

The Search menu option seems to work. Search on the top bar does not work.

**Comment by shrikan** [comment]
We found out that, the search is hitting the below url:
`http://ec2-54-187-229-255.us-west-2.compute.amazonaws.com:8983/solr/users/select?wt=json&rows=10&start=0&&facet=on&&facet.field=cause&facet.field=jobtype&facet.field=address_city&q=-id:55&fq=`

The above solr query is partial and if the input given in 'search' box is given to fq, it is giving the right value. For ex,
`http://ec2-54-187-229-255.us-west-2.compute.amazonaws.com:8983/solr/users/select?wt=json&rows=10&start=0&&facet=on&&facet.field=cause&facet.field=jobtype&facet.field=address_city&q=-id:55&fq=satish`
then it is giving the required result. Could not trace it through the code. 

_It is just the front end change and not the backend_.

**Comment by ChetanaKoulagi** [comment]
This is fixed by changing search.js
