### ISSUE TITLE
UI: Low: Menu bar disappearing

### ISSUE THREAD

**Issue by ChetanaKoulagi** [LetsTagOn/LetsTagOnThoughtClan#11]
On clicking Edit Profile, the menu bar disappears.

**Comment by ChetanaKoulagi** [comment]
The Menu bar appears on the first page of the Edit Profile Menu. But on clicking 'Next', on subsequent pages, the Menu bar is not appearing.

**Comment by sathyab28** [comment]
Tested and confirmed by Sravani
