### ISSUE TITLE
All opportunities not showing anything

### ISSUE THREAD

**Issue by sathyab28** [LetsTagOn/LetsTagOnThoughtClan#28]

**Comment by sathyab28** [comment]
Code changes done to fetch all opportunities and pagination part also done

**Comment by sathyab28** [comment]
Code committed

**Comment by ChetanaKoulagi** [comment]
Noting the below issues:
1. All Opportunities --> When I click on Opportunity name, it is not linked to any page. It should take to the Program/ Event page.
2. In the Edit Program --> Update the limit of words on Description to 250 words.
3. After the Description is limit words is changed to 250 words, check if the 'Read More' in Program Description is relevant. If not, remove Read More.
4. In the Program Details, it shows 'No Details Available'. I think it is trying to show Event Date, Time and Place. This is not relevant for a Program. Remove these.
5. In the Programs Details link, when I click on Related Events 'Read More', they should be linked to Event pages.

**Comment by sathyab28** [comment]
For 3 => I have given maximum characters 1000 

All fixed all code committed

**Comment by ChetanaKoulagi** [comment]
For 1, if I click on names from My Upcoming Events, it doesn't show descriptions. Please check.
Also, in Opportunities list, it doesnt show Created By
