### ISSUE TITLE
Edit Profile: Field/ label updates and fixes

### ISSUE THREAD

**Issue by ChetanaKoulagi** [LetsTagOn/LetsTagOnThoughtClan#35]
5 | Date of Birth not taking   properly.
6 | What type of commitment are you available for? - Change it to   just On field/ Virtual.
7 | Add a question: What best describes you? With options:   Student, Professional, Retired Professional, Home maker, Self-employed, Other   with an option to mention.
8 | Add Import from LinkedIn to Educational Details as well.
9 | Remove the question where would you like to volunteer?
10 | Skills - Rename this to "What are you good at? How would   you like to contribute?"
11 | Update Skills to: Training &   Education, Marketing & Communication, Event Participation, Event Planning   & Coordination, Fundraising, Information Technology, Finance & Legal,   Documentation & Content Development, Your Specific Hobby/ Expertise   (Mention below), Other (Mention below)
12 | Change question to "Which of the causes you feel attached   to?"
13 | Update Causes to: Education, Healthcare, Environment,   Livelihood and Skilling, Animal Welfare, Elderly Care, Differently Abled,   Child Welfare, Sports & Physical Education and Other with an option to   mention.
14 | Privacy settings do not seem to reflect. If I choose Mobile   number visibility as No, it still shows the mobile number. All these privacy   settings need to be checked and whether there is a logic behind.

**Comment by ChetanaKoulagi** [comment]
Point no. 8 and 14 - on hold for now

**Comment by sathyab28** [comment]
I have made front end changes and table update for causes and skills.

I can see the options for causes and skills in AWS app url but in local I am unable to get those options. I think some configuration or code is not updated in my branch.
