### ISSUE TITLE
Add Volunteering Experience: Field/ label updates and issues

### ISSUE THREAD

**Issue by ChetanaKoulagi** [LetsTagOn/LetsTagOnThoughtClan#37]
15 | On top of Organization Title   edit bar, say 'Role'.
16 | Cause: Make it a drop down with Causes list (with Others and   way to mention 'Others' below)
17 | Add a new field: Skill Area: Make it a drop down with Skills   list (with Others and way to mention 'Others' below)
18 | Add a new field: Number of Hours

**Comment by sathyab28** [comment]
Tested and done
