### ISSUE TITLE
Add fields to volunteer profile

### ISSUE THREAD

**Issue by ChetanaKoulagi** [LetsTagOn/LetsTagOnThoughtClan#40]
What best describes you?
Options: Student, Professional, Retired Professional, Home Maker, Self-employed, Seeking employment, Other

**Comment by ChetanaKoulagi** [comment]
Add these questions before the first question "What type of commitment are you available for?" in the first page of Edit Profile

**Comment by ChetanaKoulagi** [comment]
The second question is not needed as it is captured in Professional Experience

**Comment by sathyab28** [comment]
Changes done
