### ISSUE TITLE
Created By not showing in opportunity list

### ISSUE THREAD

**Issue by ChetanaKoulagi** [LetsTagOn/LetsTagOnThoughtClan#48]
When we click on Search --> Opportunities, Created By is empty.

**Comment by regostar** [comment]
Ok cool I'll check it

On 12 Jan 2018 11:30 am, ChetanaKoulagi <notifications@github.com> wrote:

Assigned #48<https://github.com/LetsTagOn/LetsTagOnThoughtClan/issues/48> to @regostar<https://github.com/regostar>.

**Comment by sathyab28** [comment]
Issue is fixed
